config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/news', to: 'articles#index'
  get '/contact', to: 'contacts#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: %i[show index update create]
  resources :articles, only: %i[show index]
  resources :account_activations, only: %i[edit]
  resources :password_resets, only: %i[new create edit update]
  resources :applications, only: %i[create destroy]
  resources :admin, only: %i[index]
  resources :admin_users, only: %i[index destroy]
  resources :admin_articles, only: %i[index create update destroy new edit]
  resources :admin_applications, only: %i[index destroy]
  resources :contacts, only: %i[create]

  put 'admin_users/:id', to: 'admin_users#admin'
  put 'admin_applications/:id', to: 'admin_applications#accept'
  post 'admin_applications/:id', to: 'admin_applications#reject'
end

app/controllers/admin_articles_controller.rb
class AdminArticlesController < AdminController
  def index
    @articles = Article.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @article = Article.new
  end


  def create
    @article = Article.new(user_params)
    if @article.save
      flash[:success] = "The article has been successfully added!"
      redirect_to @article
    else
      flash.now[:failure] = "Something is wrong"
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(user_params)
      flash[:success] = "The article has been successfully updated!"
      redirect_to @article
    else
      flash[:failure] = "Something is wrong"
      render 'edit'
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    flash[:success] = "Article deleted"
    redirect_to admin_articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

   private

  def user_params
    params.require(:article).permit(:title, :summary, :content,
                                    :project, :deadline, application_documents: [] )
  end
end

app/helpers/admin_articles_helper.rb
module AdminArticlesHelper
end

app/views/admin_articles/edit.html.erb
<% provide(:title, 'Update article') %>
<% provide(:btn_text, 'Update article') %>
<div class="container">
    <h3 class="materialize-red-text text-lighten-2 center">
	Update Article:
    </h3>
    <div class="section news-input">
  	<%= form_for @article, url: admin_article_path(@article) do |f| %>
	    <%= render 'shared/error-messages',object: f.object %>
	    <div class="row">
		<div class="input-field col s12">
		    <%= f.label :title %>
		    <%= f.text_field :title, class: 'form-control' %>
		</div>
	    </div>

	    <div class="row">
		<div class="input-field col s12">
		    <%= f.label :summary %>
		    <%= f.text_field :summary, class: 'form-control'%>
		</div>
	    </div>
	    <div class="row">
		<div class="input-field col s12">
		    <%= f.label :content %>
		    <%= f.text_area :content, class: "materialize-textarea form-control" %>
		</div>
	    </div>
	    <div class="row">
		<div class="input-field col s3">
		    <label>
			<%= f.check_box :project %>
			<span> Is the article about a project? </span>
		    </label>
		</div>
		<div class="input-field col s3">
		    <%= f.text_field :deadline, class: "datepicker"%>
		    <%= f.label :deadline %>
		</div>
		<div class="file-field input-field col s6">
		    <div class="btn">
			<span>Browse</span>
			<%= f.file_field :application_documents, multiple: true, direct_upload: true %>
		    </div>
		    <div class="file-path-wrapper">
			<input class="file-path validate" type="text" placeholder="Documents, forms, etc..">
		    </div>
		</div>
	    </div>
	    <div class="row">
		<div class="col s12 center">
		    <%= f.submit yield(:btn_text), class: "btn waves-effect waves-light" %>
		</div>
	    </div>
	<% end %>
    </div>

</div>

app/views/admin_articles/index.html.erb
<% provide(:title, 'News') %>
<div class="row">
    <div class="col s12 m8">
	<h3 class="materialize-red-text text-lighten-2">News' Panel</h3>
	<%= link_to(new_admin_article_path) do%>
	    <span class="btn waves-effect waves-light">Add a new article! </span>
	<% end %>
	<div class="apple_pagination">
	    <%= will_paginate @articles %>
	    <div class="news">
		<% @articles.each do |article| %>
		    <div class="card">
			<div class="card-content">
			    <span class="card-title">
				<%= link_to article.title, article, class: "materialize-red-text text-lighten-2" %>
			    </span>
			    <p class="summary">
				<span class="badge">
				    <%= article.created_at.to_s(:short)%>
				</span>
				<%= article.summary %>
			    </p>
			</div>
			<div class="card-action">
			    <%= link_to(admin_article_path(article), method: :delete,
					data: { confirm: "You sure?" }) do %>
				<i class="material-icons">delete</i>
			    <% end %>
			    <%= link_to(edit_admin_article_path(article)) do %>
				<i class="material-icons">edit</i>
			    <% end %>
			</div>
		    </div>
		<% end %>
	    </div>
	    <%= will_paginate @articles %>
	</div>
    </div>
    <div class="col s12 m4">
	<div class="dec-1 teal lighten-2"></div>
    </div>
</div>

app/views/admin_articles/new.html.erb
<% provide(:title, 'Add article') %>
<% provide(:btn_text, 'Add article') %>
<div class="container">
    <h3 class="materialize-red-text text-lighten-2 center">
	Add Article:
    </h3>
    <div class="section news-input">
	<%= form_for @article, url: admin_articles_path do |f| %>
	    <%= render 'shared/error-messages',object: f.object %>
	    <div class="row">
		<div class="input-field col s12">
		    <%= f.label :title %>
		    <%= f.text_field :title, class: 'form-control' %>
		</div>
	    </div>

	    <div class="row">
		<div class="input-field col s12">
		    <%= f.label :summary %>
		    <%= f.text_field :summary, class: 'form-control'%>
		</div>
	    </div>
	    <div class="row">
		<div class="input-field col s12">
		    <%= f.label :content %>
		    <%= f.text_area :content, class: "materialize-textarea form-control" %>
		</div>
	    </div>
	    <div class="row">
		<div class="input-field col s3">
		    <label>
			<%= f.check_box :project %>
			<span> Is the article about a project? </span>
		    </label>
		</div>
		<div class="input-field col s3">
		    <%= f.text_field :deadline, class: "datepicker"%>
		    <%= f.label :deadline %>
		</div>
		<div class="file-field input-field col s6">
		    <div class="btn">
			<span>Browse</span>
			<%= f.file_field :application_documents, multiple: true, direct_upload: true %>
		    </div>
		    <div class="file-path-wrapper">
			<input class="file-path validate" type="text" placeholder="Documents, forms, etc..">
		    </div>
		</div>
	    </div>
	    <div class="row">
		<div class="col s12 center">
		    <%= f.submit yield(:btn_text), class: "btn waves-effect waves-light" %>
		</div>
	    </div>
	<% end %>
    </div>
</div>