config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/news', to: 'articles#index'
  get '/contact', to: 'contacts#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: %i[show index update create]
  resources :articles, only: %i[show index]
  resources :account_activations, only: %i[edit]
  resources :password_resets, only: %i[new create edit update]
  resources :applications, only: %i[create destroy]
  resources :admin, only: %i[index]
  resources :admin_users, only: %i[index destroy]
  resources :admin_articles, only: %i[index create update destroy new edit]
  resources :admin_applications, only: %i[index destroy]
  resources :contacts, only: %i[create]

  put 'admin_users/:id', to: 'admin_users#admin'
  put 'admin_applications/:id', to: 'admin_applications#accept'
  post 'admin_applications/:id', to: 'admin_applications#reject'
end

app/views/admin/admin_index.html.erb
<% provide(:title, 'News Panel') %>
<div class="row">
    <div class="col s12 m8">
	<h3 class="materialize-red-text text-lighten-2">Checkout our news!</h3>
	<%= link_to(new_article_path) do%>
	    <span class="btn waves-effect waves-light">Add a new article! <i class="material-icons">add</i></span>
	<% end %>
	<ul class="collection">
	    <% @articles.reverse_each do |article| %>
		<li class="collection-item">
		    <div>
			<span class="chip">
			    <%= article.created_at.to_s(:short)%>
			</span>
			<%= article.title %>
			
			<%= link_to(article) do %>
			    <span class="secondary-content"><i class="material-icons">send</i></span>
			<% end %>
			<%= link_to(article, method: :delete, data: { confirm: "You sure?" }) do %>
			    <span class="secondary-content"><i class="material-icons">delete</i></span>
			<% end %>
			<%= link_to(edit_article_path(article)) do %>
			    <span class="secondary-content"><i class="material-icons">edit</i></span>
			<% end %>
		    </div>
		</li>
	    <% end %>
	</ul>
    </div>
    <div class="col s12 m4">
	<div class="dec-1 teal lighten-2"></div>
    </div>
</div>

app/views/admin/index.html.erb
<% provide(:title, 'Admin Panel') %>
<h3 class="materialize-red-text text-lighten-2">
    Welcome to the Admin Panel, please be careful
</h3>
<blockquote>
    With great power comes great Responsibility -- Uncle Ben
</blockquote>

<div class="row">
    <div class="col s12 m8 push-m2">
    <% if !@applications.blank? %>    
	<div class="pending-applications card-panel materialize-red lighten-3">
	    <span class="white-text">There are <%= @applications.length %> applications pending.</span>
	</div>
    <% end %>
    </div>
</div>


<div class="row">
    <div class="col s12 m4">
	<div class="card horizontal">
            <div class="card-image">
		<i class="material-icons center large">face</i>
		<%= link_to(admin_users_path) do %>
		    <div class="btn-floating halfway-fab waves-effect waves-light teal">
			<i class="material-icons">add</i>
		    </div>
		<% end %>
	    </div>
            <div class="card-content">
		<h6>Users' panel</h6>
		<p>Here you can delete users, give them admin rights
		    and view their applications.</p>
	    </div>
        </div>
    </div>
    <div class="col s12 m4">
	<div class="card horizontal">
            <div class="card-image">
		<i class="material-icons center large">assignment</i>
		<%= link_to(admin_articles_path) do %>
		    <div class="btn-floating halfway-fab waves-effect waves-light teal">
			<i class="material-icons">add</i>
		    </div>
		<% end %>
	    </div>
            <div class="card-content">
		<h6>News' panel</h6>
		<p>Add news, edit old ones, delete wrong ones. In
		    general make stuff with articles.</p>
	    </div>
        </div>
    </div>
    <div class="col s12 m4">
	<div class="card horizontal">
            <div class="card-image">
		<i class="material-icons center large">card_travel</i>
		<%= link_to(admin_applications_path) do %>
		    <div class="btn-floating halfway-fab waves-effect waves-light teal">
			<i class="material-icons">add</i>
		    </div>
		<% end %>
	    </div>
            <div class="card-content">
		<h6>Applications' panel</h6>
		<p>Gather the filled in documents and approve
		    appropriate applications. Nepotism at its best.</p>
	    </div>
	</div>
    </div>
</div>