config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/news', to: 'articles#index'
  get '/contact', to: 'contacts#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: %i[show index update create]
  resources :articles, only: %i[show index]
  resources :account_activations, only: %i[edit]
  resources :password_resets, only: %i[new create edit update]
  resources :applications, only: %i[create destroy]
  resources :admin, only: %i[index]
  resources :admin_users, only: %i[index destroy]
  resources :admin_articles, only: %i[index create update destroy new edit]
  resources :admin_applications, only: %i[index destroy]
  resources :contacts, only: %i[create]

  put 'admin_users/:id', to: 'admin_users#admin'
  put 'admin_applications/:id', to: 'admin_applications#accept'
  post 'admin_applications/:id', to: 'admin_applications#reject'
end

app/controllers/admin_users_controller.rb
class AdminUsersController < AdminController
  include SessionsHelper

  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)
    store_location
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_back_or root_path
  end

  def admin
    user = User.find(params[:id])
    if user.admin
      user.update_attribute(:admin, FALSE)
      flash[:success] = 'User has been denied superpowers'
    else
      user.update_attribute(:admin, TRUE)
      flash[:success] = 'User has been granted superpowers'
    end
    redirect_to admin_users_path
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/index.html.erb
<% provide(:title, 'Users Panel') %>

<h3 class="materialize-red-text text-lighten-2">
    Users' Panel
</h3>
<h6> Click any user to see his applications </h6>

<%= will_paginate @users %>
<ul class="collapsible popout">
    <% @users.each do |user| %>
	<li>
	    <div class="collapsible-header">
		<span>
		    <a href="mailto:<%= user.email %>"><%= material_icon.email.md_24 %></a>
		    <% if user.admin? %>
			<i class="material-icons materialize-red-text">gavel</i>
		    <% end %>
		</span>
		
		<%= user.name %>, joined at    <%= user.created_at.to_s(:long) %>
		
		<span class="badge right">
		    <%= link_to(admin_user_path(user), method: :delete, data: { confirm: "You sure?" }) do %>
			<i class="material-icons">delete</i>
		    <% end %>
		    
		    <%= link_to(admin_user_path(user), method: :put, data: { confirm: "Are you sure?"}) do %>
			<i class="material-icons">build</i>
		    <% end %>
		    No of applications <%= user.applications.length %>
		</span>
	    </div>

	    <div class="collapsible-body">
		<% if !user.applications.blank?  %>
		    <table>
			<thead>
			    <tr>
				<th> Applied for </th>
				<th> Status </th>
				<th> Files </th>
				<th> Manage Applications </th>
			    </tr>
			</thead>
			<% user.applications.each do |application| %>
			    <% article = Article.find(application.article_id) %>
			    <tbody>
				<tr>
				    <td> <%= link_to article.title, article_path(application.article_id) %> </td>
				    <td> <%= application.progress %> </td>
				    <% if application.application_document.attached? %>
					<td>
					    <%= link_to application.application_document.filename,
					    application.application_document %>
					</td>
				    <% else %>
					<td>
					</td>
				    <% end %>
				    <td>
					link_to application_admin_path(application_id)
				    </td>
				</tr>
			    </tbody>
			<% end %>
		    </table>
		<% end %>
	    </div>
	</li>
    <% end %>
</ul>
<%= will_paginate @users %>