config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/news', to: 'articles#index'
  get '/contact', to: 'contacts#new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: %i[show index update create]
  resources :articles, only: %i[show index]
  resources :account_activations, only: %i[edit]
  resources :password_resets, only: %i[new create edit update]
  resources :applications, only: %i[create destroy]
  resources :admin, only: %i[index]
  resources :admin_users, only: %i[index destroy]
  resources :admin_articles, only: %i[index create update destroy new edit]
  resources :admin_applications, only: %i[index destroy]
  resources :contacts, only: %i[create]

  put 'admin_users/:id', to: 'admin_users#admin'
  put 'admin_applications/:id', to: 'admin_applications#accept'
  post 'admin_applications/:id', to: 'admin_applications#reject'
end

app/views/layouts/_contact-modal.html.erb
<div id="modal-contact" class="modal">
    <div class="modal-content">
	<div class="row">
	    <form class="col s12">
		<div class="row">
		    <div class="input-field col s6">
			<i class="material-icons prefix">account_circle</i>
			<input id="name" type="text" class="validate">
			<label for="name"> Your name </label>
		    </div>
		    <div class="input-field col s6">
			<i class="material-icons prefix">email</i>
			<input id="email" type="email" class="validate">
			<label for="email"> Your email </label>
		    </div>
		</div>
		<div class="row">
		    <div class="input-field col s12">
			<i class="material-icons prefix">subject</i>
			<input id="subject" type="text" class="validate">
			<label for="name"> Subject </label>
		    </div>
		</div>
		<div class="row">
		    <div class="input-field col s12">
			<i class="material-icons prefix">mode_edit</i>
			<textarea id="text1" class="materialize-textarea"></textarea>
			<label for="text1"> Message </label>
		    </div>
		</div>
		<div class="modal-footer">
		    <button class="btn waves-effect waves-light right" type="submit" name="action">Submit
			<i class="material-icons right">send</i>
		    </button>
		</div>
	    </form>
	</div>
    </div>
</div>			    

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <script>
     var msg = '<%= message %>';
     M.toast({html: msg, classes: 'alert'});
    </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer center">
    <h6>contact us by</h6>
    <h6>following us on <a href="https://www.facebook.com/BreakTheBordersNGO/">facebook</a> </h6>
    <p> ======================================= </p>
    <h6>or via e-mail</h6>
    <a href="mailto:breaktheborders@yahoo.com"><%= material_icon.email.md_24 %></a>
    <a href="/contact"><%= material_icon.message.md_24 %></a>
    <div class="footer-copyright">
	<h6> made with love by bendersteed <%= material_icon.favorite.md_18 %> </h6>
	<h6> <%= material_icon.copyright.md_18 %>  Break the Borders, 2019 </h6>
    </div>
</footer>

app/views/layouts/_head.html.erb
<head>
    <title><%= full_title(yield(:title)) %></title>
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker|Roboto" rel="stylesheet"> 
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="/assets/minit.js" defer data-turbolinks-eval="false"></script>
</head>

app/views/layouts/_header.html.erb
<header>
    <% if logged_in? %>
	<ul id="account-dropdown" class="dropdown-content materialize-red lighten-3">
	    <li><%= link_to "Account", user_path(current_user) %></li>
	    <li class="divider"></li>
	    <li> <%= link_to "Log out", logout_path, method: :delete %> </li>
	</ul>
    <% end %>
    
    <ul id="slide-out" class="sidenav">
	<li><a href ="#" class="brand-logo flow-text materialize-red-text text-lighten-2">Break the borders</a></li>
	<li><div class="divider"></div></li>
	<% if logged_in? and admin? %>
	    <li class="<%= active?("/admin") %>"><%= link_to "Admin", '/admin' %></li>
	<% end %>
	<li class="<%= active?(root_path) %>"><%= link_to "Home", root_path %></li>
	<li class="<%= active?(news_path)%>"><%= link_to "News", news_path %></li>
	<li class="<%= active?(about_path) %>"><%= link_to "About", about_path %></li>
	<li class="<%= active?(contact_path)%>>"<%= link_to "Contact", contact_path%></li>
	<% if logged_in? %>
	    <li class="no-padding">
		<ul class="collapsible collapsible-accordion">
		    <li>
			<a class="collapsible-header">
			    <i class="material-icons left">account_circle</i>
			    <%= current_user[:name] %>
			    <i class="material-icons">arrow_drop_down</i>
			</a>
			<div class="collapsible-body">
			    <ul>
				<li><%= link_to "Account", user_path(current_user) %></li>
				<li class="divider"></li>
				<li> <%= link_to "Log out", logout_path, method: :delete %> </li>
			    </ul>
			</div>
		    </li>
		</ul>
	    </li>
	<% else %>
	    <li><%= link_to "Log in", login_path %></li>
	<% end %>
    </ul>
    
    
    <nav>
	<div class="nav-wrapper">
	    <a href="#" data-target="slide-out" class="sidenav-trigger show-on-small">
		<i class="material-icons">menu</i>
	    </a>
	    <a href ="#" class="brand-logo flow-text hide-on-small-only">Break the borders</a>
	    <a href ="#" class="brand-logo flow-text hide-on-med-and-up">BtB</a>
	    <ul id="nav-mobile" class="right hide-on-med-and-down">
		<% if logged_in? and admin? %>
		    <li class="<%= active?("/admin") %>">
			<%= link_to('/admin') do %>
			    <% if !Application.where(progress: 'pending').blank? %>
				<span class="new badge">
				    <%= Application.where(progress: 'pending').length %>
				</span>
			    <% end %>
			    Admin
			<% end %>
		    </li>
		<% end %>
		<li class="<%= active?(root_path) %>"><%= link_to "Home", root_path %></li>
		<li class="<%= active?(news_path)%>"><%= link_to "News", news_path %></li>
		<li class="<%= active?(about_path) %>"><%= link_to "About", about_path %></li>
		<li class="<%= active?(contact_path)%>"><%= link_to "Contact", contact_path %></li>
		<% if logged_in? %>
		    <li>
			<a class="dropdown-trigger" href="#!" data-target="account-dropdown">
			    <i class="material-icons left">account_circle</i>
			    <%= current_user[:name] %>
			</a>
		    </li>
		<% else %>
		    <li><%= link_to "Log in", login_path %></li>
		<% end %>
	    </ul>
	</div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <%= render 'layouts/head' %>
    <body>
	<%= render 'layouts/header' %>
	<main class="container">
		<%= render 'layouts/flash' %>
		<%= yield %>
	</main>
	    <%= render 'layouts/footer' %>
	    <%= render 'layouts/contact-modal' %>
    </body>
</html>